### ISSUE TITLE
401 Unauthorized /api/v1/signingCert

### ISSUE THREAD

**Issue by mi1wei** [sigstore/fulcio#1022] opened 2023-02-27 03:10 UTC
**Description**

when i use enterprise github action, i got failed. 
when i use github action, it works righly.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/32791982/221463892-9d6e4b94-d470-443d-8602-a2a756821a44.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/32791982/221464276-ce80010c-15a2-475c-92d6-d0b85b05e63c.png">

**Version**

v2

**Comment by znewman01** [comment] 2023-02-27 14:47
When you say "enterprise GitHub action," are you using a self-hosted runner? 

If so, this is expected. The Cosign integration in Goreleaser uses ephemeral keys, which use your GitHub credentials to get a signing certificate from Fulcio to sign your release. The public Fulcio instance doesn't (and probably won't) support credentials from self-hosted runners.

If not, we  still probably won't be able to do anything here. I found some details: https://docs.github.com/en/enterprise-cloud@latest/rest/actions/oidc?apiVersion=2022-11-28

It looks like you GitHub Actions Enterprise lets you customize the way OIDC issuance works pretty heavily, which means that we won't be able to verify conformance with these requirements: https://github.com/sigstore/fulcio/issues/397

That said, you can always spin up your own Fulcio instance and configure it to accept GHES OIDC tokens. It's a fair bit of work, but hopefully that will change in the longer run.

**Comment by haydentherapper** [comment] 2023-02-27 15:28
Closing as working as intended, there isn’t support for enterprise instances of GitHub.

**Closed by haydentherapper** 2023-02-27 15:28 UTC
Labels: bug
